package com.xing.entity;

public class Association {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column association.acid
     *
     * @mbg.generated Sun Sep 03 20:13:49 CST 2017
     */
    private Integer acid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column association.aid
     *
     * @mbg.generated Sun Sep 03 20:13:49 CST 2017
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column association.cid
     *
     * @mbg.generated Sun Sep 03 20:13:49 CST 2017
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column association.acid
     *
     * @return the value of association.acid
     *
     * @mbg.generated Sun Sep 03 20:13:49 CST 2017
     */
    public Integer getAcid() {
        return acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column association.acid
     *
     * @param acid the value for association.acid
     *
     * @mbg.generated Sun Sep 03 20:13:49 CST 2017
     */
    public void setAcid(Integer acid) {
        this.acid = acid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column association.aid
     *
     * @return the value of association.aid
     *
     * @mbg.generated Sun Sep 03 20:13:49 CST 2017
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column association.aid
     *
     * @param aid the value for association.aid
     *
     * @mbg.generated Sun Sep 03 20:13:49 CST 2017
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column association.cid
     *
     * @return the value of association.cid
     *
     * @mbg.generated Sun Sep 03 20:13:49 CST 2017
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column association.cid
     *
     * @param cid the value for association.cid
     *
     * @mbg.generated Sun Sep 03 20:13:49 CST 2017
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}